services:
  api:
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - VITE_API_URL=http://web-users-demo.local/api/v1
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
